apiVersion: v1
kind: Pod
metadata:
  name: env
  labels:
    project: expense
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          value: devops
        - name: trainer
          value: siva kumar
        - name: duration
          value: 120 hrs
