apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap
  labels:
    environment: dev
    project: expense
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: 100m
          memory: 68Mi
        limits:
          cpu: 120m
          memory: 120Mi
      env:
        - name: course
          valueFrom:
            configMapKeyRef:
              key: course
        - name: duration
          valueFrom:
            configMapKeyRef:
              key: duration